# Generated by Django 5.0 on 2024-01-29 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_city_roles_state_status_user_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='Address',
        ),
        migrations.AddField(
            model_name='address',
            name='House_Add',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='Landmark',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='Street_Add',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='City',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.city'),
        ),
    ]
