# Generated by Django 5.0 on 2024-01-06 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theater_M',
            fields=[
                ('T_ID', models.AutoField(primary_key=True, serialize=False)),
                ('T_Name', models.CharField(max_length=50)),
                ('T_Flat_Add', models.CharField(max_length=200)),
                ('T_Street_Add', models.CharField(max_length=200)),
                ('T_Pin', models.IntegerField()),
                ('T_Open_Date', models.DateField()),
                ('T_No_Of_Screen', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('Theater_Manager_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
