# Generated by Django 5.0 on 2024-01-06 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBtheatersAndBooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('Seat_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('Seat_type_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Screen_M',
            fields=[
                ('Screen_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Screen_Total_Seats', models.IntegerField()),
                ('T_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBtheatersAndBooking.theater_m')),
            ],
        ),
        migrations.CreateModel(
            name='Seat_M',
            fields=[
                ('Seat_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Seat_No', models.CharField(max_length=5)),
                ('Seat_Status', models.BooleanField(default=False)),
                ('Screen_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBtheatersAndBooking.screen_m')),
                ('Seat_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBtheatersAndBooking.seattype')),
            ],
        ),
    ]
