# Generated by Django 5.0 on 2024-01-08 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBmovies', '0004_movie_cast_m_movie_genre_m_movie_language_m_and_more'),
        ('MBtheatersAndBooking', '0002_seattype_screen_m_seat_m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Mode',
            fields=[
                ('Payment_Mode_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Payment_Mode_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='seat_m',
            old_name='Seat_No',
            new_name='Seat_Row_AlphaBet',
        ),
        migrations.AddField(
            model_name='seat_m',
            name='Seat_Col_Num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seat_m',
            name='Seat_Row_Num',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Booking_M',
            fields=[
                ('B_ID', models.AutoField(primary_key=True, serialize=False)),
                ('B_Time', models.TimeField()),
                ('B_Date', models.DateField()),
                ('SubTotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('TotalAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Payment_Mode_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBtheatersAndBooking.payment_mode')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_Seat_M',
            fields=[
                ('Booking_Seat_ID', models.AutoField(primary_key=True, serialize=False)),
                ('B_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBtheatersAndBooking.booking_m')),
                ('Seat_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBtheatersAndBooking.seat_m')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_MB',
            fields=[
                ('Complaint_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Complaint_Desc', models.TextField()),
                ('Complaint_Date', models.DateTimeField(auto_now_add=True)),
                ('M_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MBmovies.movie_m')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShowTime_M',
            fields=[
                ('ShowTime_ID', models.AutoField(primary_key=True, serialize=False)),
                ('StartTime', models.TimeField()),
                ('Date', models.DateField()),
                ('M_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBmovies.movie_m')),
                ('Screen_M', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBtheatersAndBooking.screen_m')),
            ],
        ),
        migrations.CreateModel(
            name='SeatPrice',
            fields=[
                ('SeatPrice_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Seat_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBtheatersAndBooking.seattype')),
                ('ShowTime_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBtheatersAndBooking.showtime_m')),
            ],
        ),
        migrations.AddField(
            model_name='booking_m',
            name='ShowTime_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBtheatersAndBooking.showtime_m'),
        ),
    ]
