# Generated by Django 5.0 on 2024-01-09 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBmovies', '0004_movie_cast_m_movie_genre_m_movie_language_m_and_more'),
        ('MBtheatersAndBooking', '0004_screen_m_screen_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime_m',
            name='M_Language_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MBmovies.movie_language'),
        ),
    ]
