# Generated by Django 5.0 on 2024-01-09 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MBtheatersAndBooking', '0005_showtime_m_m_language_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime_m',
            name='M_Language_ID',
        ),
    ]
