# Generated by Django 5.0 on 2024-01-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBtheatersAndBooking', '0006_remove_showtime_m_m_language_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_m',
            name='SubTotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
