# Generated by Django 5.0 on 2024-01-10 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBtheatersAndBooking', '0007_alter_booking_m_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat_m',
            name='Seat_Status',
        ),
        migrations.AlterField(
            model_name='booking_m',
            name='TotalAmt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='screen_m',
            name='T_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='MBtheatersAndBooking.theater_m'),
        ),
        migrations.AlterField(
            model_name='showtime_m',
            name='Screen_M',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='MBtheatersAndBooking.screen_m'),
        ),
        migrations.CreateModel(
            name='SeatInShowtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_booked', models.BooleanField(default=False)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBtheatersAndBooking.seat_m')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBtheatersAndBooking.showtime_m')),
            ],
        ),
    ]
