# Generated by Django 5.0 on 2024-01-11 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBtheatersAndBooking', '0008_remove_seat_m_seat_status_alter_booking_m_totalamt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_mb',
            name='T_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MBtheatersAndBooking.theater_m'),
        ),
    ]
