# Generated by Django 5.0 on 2024-01-12 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBtheatersAndBooking', '0009_complaint_mb_t_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_seat_m',
            name='Seat_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBtheatersAndBooking.seatinshowtime'),
        ),
    ]
