# Generated by Django 5.0 on 2024-01-12 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBtheatersAndBooking', '0012_alter_booking_seat_m_seat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_m',
            name='Payment_Mode_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MBtheatersAndBooking.payment_mode'),
        ),
        migrations.AlterField(
            model_name='booking_m',
            name='SubTotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
