# Generated by Django 5.0 on 2024-01-12 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBtheatersAndBooking', '0013_alter_booking_m_payment_mode_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_seat_m',
            name='B_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_seat_m_set', to='MBtheatersAndBooking.booking_m'),
        ),
    ]
