# Generated by Django 5.0 on 2024-01-13 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBtheatersAndBooking', '0014_alter_booking_seat_m_b_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_m',
            name='B_Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking_m',
            name='B_Time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='seatprice',
            name='Seat_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seatprice_set', to='MBtheatersAndBooking.seattype'),
        ),
    ]
