# Generated by Django 5.0 on 2024-01-13 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MBtheatersAndBooking', '0016_showtime_m_m_language_showtime_m_m_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime_m',
            name='M_Language',
        ),
        migrations.RemoveField(
            model_name='showtime_m',
            name='M_Type',
        ),
    ]
