# Generated by Django 5.0 on 2024-04-09 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBmovies', '0005_movie_type_m_movie_type'),
        ('MBtheatersAndBooking', '0019_theater_m_city_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate_MB',
            fields=[
                ('Rate_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Rate_Movie', models.CharField(blank=True, max_length=10, null=True)),
                ('M_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MBmovies.movie_m')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
