# Generated by Django 5.0 on 2024-04-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBtheatersAndBooking', '0020_rate_mb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate_mb',
            name='Rate_Movie',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
