# Generated by Django 5.0 on 2024-04-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBtheatersAndBooking', '0021_alter_rate_mb_rate_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate_mb',
            name='Rate_Movie',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
