# Generated by Django 5.0 on 2024-01-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicStreaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_m',
            name='cover',
            field=models.ImageField(default='default_image.jpg', upload_to='music_cover/'),
        ),
    ]
