# Generated by Django 5.0 on 2024-01-29 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicStreaming', '0002_music_m_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album_m',
            name='No_Of_Songs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album_m',
            name='ReleaseDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='artist_m',
            name='Date_Joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='artist_m',
            name='MS_Genre_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MusicStreaming.ms_genre_m'),
        ),
        migrations.AlterField(
            model_name='music_m',
            name='Release_Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='playlist_m',
            name='P_Created_Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
