# Generated by Django 5.0 on 2024-02-03 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicStreaming', '0005_alter_music_m_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedMusic_Plalist',
            fields=[
                ('LikedMusic_Plalist_ID', models.AutoField(primary_key=True, serialize=False)),
                ('P_Created_Date', models.DateField(auto_now_add=True)),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikedMusic',
            fields=[
                ('PlaylistMusic_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Music_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicStreaming.music_m')),
                ('LikedMusic_Plalist_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicStreaming.likedmusic_plalist')),
            ],
        ),
    ]
