# Generated by Django 5.0 on 2024-02-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicStreaming', '0006_likedmusic_plalist_likedmusic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album_m',
            name='No_Of_Songs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
