# Generated by Django 5.0 on 2024-02-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicStreaming', '0007_alter_album_m_no_of_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music_m',
            name='M_Streams',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
