# Generated by Django 5.0 on 2024-02-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicStreaming', '0008_alter_music_m_m_streams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music_m',
            name='M_Streams',
            field=models.IntegerField(default=0),
        ),
    ]
