# Generated by Django 5.0 on 2024-02-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicStreaming', '0009_alter_music_m_m_streams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics_m',
            name='TotalStreams',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
