# Generated by Django 5.0 on 2024-03-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicStreaming', '0011_alter_music_artist_artist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music_m',
            name='M_Streams',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
