# Generated by Django 5.0 on 2024-04-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicStreaming', '0012_alter_music_m_m_streams'),
    ]

    operations = [
        migrations.AddField(
            model_name='album_m',
            name='cover',
            field=models.ImageField(default='default_image.jpg', upload_to='album_cover/'),
        ),
    ]
