# Generated by Django 5.0 on 2024-04-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicStreaming', '0013_album_m_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist_m',
            name='Artist_Profile_Picture',
            field=models.ImageField(default='default_image.jpg', upload_to='artist_profile_picture/'),
        ),
    ]
