from django.contrib import admin
from .models import *
admin.site.register(Movie_M)
admin.site.register(Movie_Img)
admin.site.register(Movie_Director_M)
admin.site.register(Movie_Director)
admin.site.register(Movie_Producer_M)
admin.site.register(Movie_Producer)
admin.site.register(Movie_Cast_M)
admin.site.register(Movie_Cast)
admin.site.register(Movie_Genre_M)
admin.site.register(Movie_Genre)
admin.site.register(Movie_Language_M)
admin.site.register(Movie_Language)
admin.site.register(Movie_Type_M)
admin.site.register(Movie_Type)