# Generated by Django 5.0 on 2024-01-05 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBmovies', '0003_movie_director_m_alter_movie_img_img_movie_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Cast_M',
            fields=[
                ('Cast_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Cast_Name', models.CharField(max_length=50)),
                ('Cast_img', models.ImageField(default='default_image.jpg', upload_to='Movie_Cast_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Genre_M',
            fields=[
                ('Genre_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Genre_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Language_M',
            fields=[
                ('Language_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Language_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Producer_M',
            fields=[
                ('Producer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Producer_Name', models.CharField(max_length=50)),
                ('Producer_img', models.ImageField(default='default_image.jpg', upload_to='Movie_Producer_images/')),
            ],
        ),
        migrations.RenameField(
            model_name='movie_director',
            old_name='D_ID',
            new_name='Director_ID',
        ),
        migrations.RenameField(
            model_name='movie_director_m',
            old_name='D_ID',
            new_name='Director_ID',
        ),
        migrations.RenameField(
            model_name='movie_director_m',
            old_name='D_Name',
            new_name='Director_Name',
        ),
        migrations.RenameField(
            model_name='movie_director_m',
            old_name='img',
            new_name='Director_img',
        ),
        migrations.CreateModel(
            name='Movie_Cast',
            fields=[
                ('MCast_ID', models.AutoField(primary_key=True, serialize=False)),
                ('M_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBmovies.movie_m')),
                ('Cast_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBmovies.movie_cast_m')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Genre',
            fields=[
                ('MGenre_ID', models.AutoField(primary_key=True, serialize=False)),
                ('M_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBmovies.movie_m')),
                ('Genre_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBmovies.movie_genre_m')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Language',
            fields=[
                ('MLanguage_ID', models.AutoField(primary_key=True, serialize=False)),
                ('M_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBmovies.movie_m')),
                ('Language_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBmovies.movie_language_m')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Producer',
            fields=[
                ('Mp_ID', models.AutoField(primary_key=True, serialize=False)),
                ('M_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBmovies.movie_m')),
                ('Producer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBmovies.movie_producer_m')),
            ],
        ),
    ]
