# Generated by Django 5.0 on 2024-01-13 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBmovies', '0004_movie_cast_m_movie_genre_m_movie_language_m_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Type_M',
            fields=[
                ('Type_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Type_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Type',
            fields=[
                ('MType_ID', models.AutoField(primary_key=True, serialize=False)),
                ('M_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBmovies.movie_m')),
                ('Type_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBmovies.movie_type_m')),
            ],
        ),
    ]
