# Generated by Django 5.0 on 2024-01-03 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('Categories_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Categories_Name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Color_M',
            fields=[
                ('Color_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Color_Name', models.CharField(max_length=24)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Size_M',
            fields=[
                ('Size_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Size_Name', models.CharField(max_length=8)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Color',
            fields=[
                ('P_Color_ID', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.product_color_m')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Img',
            fields=[
                ('Img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(default='default_image.jpg', upload_to='product_images/')),
                ('product_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecom.product_color')),
            ],
        ),
        migrations.CreateModel(
            name='Product_M',
            fields=[
                ('P_ID', models.AutoField(primary_key=True, serialize=False)),
                ('P_Name', models.CharField(max_length=90)),
                ('P_Desc', models.TextField(blank=True, null=True)),
                ('P_Price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.categories')),
            ],
        ),
        migrations.AddField(
            model_name='product_color',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.product_m'),
        ),
        migrations.CreateModel(
            name='Product_Size',
            fields=[
                ('P_Size_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Stock', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.product_color')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.product_size_m')),
            ],
        ),
    ]
