# Generated by Django 5.0 on 2024-02-10 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0002_remove_product_img_product_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer_M',
            fields=[
                ('Offer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Offer_Title', models.CharField(max_length=50)),
                ('Offer_Desc', models.CharField(max_length=120)),
                ('DiscountPercentage', models.IntegerField()),
                ('MaximumDiscount', models.IntegerField(null=True)),
                ('MinimumTotalAmt', models.IntegerField(null=True)),
                ('MinimumProduct', models.IntegerField(null=True)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Mode',
            fields=[
                ('Payment_Mode_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Payment_Mode_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status_M',
            fields=[
                ('Status_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Status_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder_M',
            fields=[
                ('Reminder_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Reminder_Date', models.DateField()),
                ('Product_Size_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.product_size')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist_M',
            fields=[
                ('Wishlist_ID', models.AutoField(primary_key=True, serialize=False)),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist_Details',
            fields=[
                ('Wishlist_Item_ID', models.AutoField(primary_key=True, serialize=False)),
                ('P_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.product_m')),
                ('Wishlist_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='Ecom.wishlist_m')),
            ],
        ),
    ]
