# Generated by Django 5.0 on 2024-03-13 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0003_offer_m_payment_mode_status_m_reminder_m_wishlist_m_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_RateReview_M',
            fields=[
                ('Rate_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Rate', models.CharField(max_length=5)),
                ('Review', models.TextField()),
                ('RateReview_Date', models.DateTimeField(auto_now_add=True)),
                ('P_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.product_m')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
