# Generated by Django 5.0 on 2024-03-14 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0004_product_ratereview_m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_M',
            fields=[
                ('CartID', models.AutoField(primary_key=True, serialize=False)),
                ('Total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Details',
            fields=[
                ('CartDetailsID', models.AutoField(primary_key=True, serialize=False)),
                ('ItemQuantity', models.IntegerField()),
                ('Subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.product_m')),
                ('Cart_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.cart_m')),
            ],
        ),
    ]
