# Generated by Django 5.0 on 2024-03-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0005_cart_m_cart_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_details',
            old_name='Product_ID',
            new_name='P_ID',
        ),
    ]
