# Generated by Django 5.0 on 2024-03-20 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0006_rename_product_id_cart_details_p_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_M',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateTimeField()),
                ('Total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Status_ID', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ecom.status_m')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('OrderDetailsID', models.AutoField(primary_key=True, serialize=False)),
                ('ItemQuantity', models.IntegerField()),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('P_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.product_m')),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.order_m')),
            ],
        ),
    ]
