# Generated by Django 5.0 on 2024-03-20 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0007_order_m_order_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_m',
            name='Status_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ecom.status_m'),
        ),
    ]
