# Generated by Django 5.0 on 2024-03-20 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0008_alter_order_m_status_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_details',
            name='Size_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecom.product_size'),
        ),
    ]
