# Generated by Django 5.0 on 2024-04-12 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0014_alter_order_details_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint_EC',
            fields=[
                ('Complaint_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Complaint_Desc', models.CharField(max_length=250)),
                ('Complaint_Date', models.DateField(auto_now_add=True)),
                ('Order_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecom.order_m')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
