# Generated by Django 5.0 on 2024-04-13 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0015_complaint_ec'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist_m',
            name='P_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecom.product_m'),
        ),
        migrations.AddField(
            model_name='wishlist_m',
            name='Wishlist_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Wishlist_Details',
        ),
    ]
