# Generated by Django 5.0 on 2024-04-21 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0016_wishlist_m_p_id_wishlist_m_wishlist_date_and_more'),
        ('account', '0004_alter_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_m',
            name='Address_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.address'),
        ),
    ]
